name: PR Todo Checker

on:
    pull_request_review_comment:
        types: [edited, deleted]
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    find_todos:
        runs-on: ubuntu-latest
        # don't run on draft PRs
        if: github.event.pull_request.draft == false

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Check for Todos
              uses: phntmxyz/pr_todo_checker@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
